import type { Market } from './types';

export const DEFAULT_MARKETS: Market[] = [
  {
    handle: 'middle-east',
    name: 'Middle East',
    type: 'regional',
    countries: ['AE', 'SA', 'QA', 'KW', 'BH', 'OM', 'JO', 'LB', 'IL', 'EG', 'TR'],
    primaryCurrency: 'USD',
    alternativeCurrencies: [],
    primaryLanguage: 'en',
    alternativeLanguages: ['ar'],
    enabled: true,
  },
  {
    handle: 'united-states',
    name: 'United States',
    type: 'regional',
    countries: ['US'],
    primaryCurrency: 'USD',
    alternativeCurrencies: [],
    primaryLanguage: 'en',
    alternativeLanguages: [],
    enabled: true,
  },
  {
    handle: 'greater-china',
    name: 'Greater China',
    type: 'regional',
    countries: ['HK', 'CN', 'MO', 'TW'],
    primaryCurrency: 'USD',
    alternativeCurrencies: ['HKD', 'CNY'],
    primaryLanguage: 'en',
    alternativeLanguages: ['zh'],
    enabled: true,
  },
  {
    handle: 'south-east-asia',
    name: 'South East Asia',
    type: 'regional',
    countries: ['SG', 'MY', 'TH', 'ID', 'PH', 'BN', 'KH', 'LA', 'MM'],
    primaryCurrency: 'USD',
    alternativeCurrencies: [],
    primaryLanguage: 'en',
    alternativeLanguages: [],
    enabled: true,
  },
  {
    handle: 'japan',
    name: 'Japan',
    type: 'regional',
    countries: ['JP'],
    primaryCurrency: 'JPY',
    alternativeCurrencies: ['USD'],
    primaryLanguage: 'ja',
    alternativeLanguages: ['en'],
    enabled: true,
  },
  {
    handle: 'korea',
    name: 'Korea',
    type: 'regional',
    countries: ['KR'],
    primaryCurrency: 'KRW',
    alternativeCurrencies: ['USD'],
    primaryLanguage: 'ko',
    alternativeLanguages: ['en'],
    enabled: true,
  },
  {
    handle: 'oceania',
    name: 'Oceania',
    type: 'regional',
    countries: ['AU', 'NZ'],
    primaryCurrency: 'AUD',
    alternativeCurrencies: ['NZD'],
    primaryLanguage: 'en',
    alternativeLanguages: [],
    enabled: true,
  },
  {
    handle: 'canada',
    name: 'Canada',
    type: 'regional',
    countries: ['CA'],
    primaryCurrency: 'CAD',
    alternativeCurrencies: ['USD'],
    primaryLanguage: 'en',
    alternativeLanguages: ['fr'],
    enabled: true,
  },
  {
    handle: 'europe',
    name: 'Europe',
    type: 'regional',
    countries: ['DE', 'FR', 'IT', 'ES', 'NL', 'BE', 'AT', 'PT', 'IE', 'FI', 'SE', 'DK', 'PL', 'CZ', 'GR', 'HU', 'RO', 'SK', 'SI', 'LU', 'EE', 'LV', 'LT', 'BG', 'HR', 'MT', 'CY', 'GB', 'CH', 'NO'],
    primaryCurrency: 'EUR',
    alternativeCurrencies: ['GBP', 'CHF', 'NOK'],
    primaryLanguage: 'en',
    alternativeLanguages: ['de', 'fr', 'it', 'es'],
    enabled: true,
  },
  {
    handle: 'vietnam-domestic',
    name: 'Vietnam (Domestic)',
    type: 'regional',
    countries: ['VN'],
    primaryCurrency: 'VND',
    alternativeCurrencies: [],
    primaryLanguage: 'vi',
    alternativeLanguages: ['en'],
    enabled: true,
  },
  {
    handle: 'international',
    name: 'International',
    type: 'international',
    countries: [],
    primaryCurrency: 'USD',
    alternativeCurrencies: [],
    primaryLanguage: 'en',
    alternativeLanguages: [],
    enabled: true,
  },
];
